<?php
function getTestUserBySector(){
    $userId= get_current_user_id();
    $userMeta = get_user_meta( $userId);
    $query_array = array(
        'post_type' => 'settore',
        //Showing all posts
        'posts_per_page' => -1,
        //Giving all child posts only
        'post_parent__not_in' => array( 0 )
    );
    $the_query = new WP_Query($query_array);
    //Array to collect all parent posts
    $collect_parents = array();
    while($the_query->have_posts()):
        $the_query->the_post();
        $sectorsParentId = wp_get_post_parent_id(get_the_ID());
        //if condition is used to eliminate duplicates, generated by same child post of parent.
        if(!in_array($sectorsParentId, $collect_parents)){
            //$collect_parents contains all the parent post id's
            $collect_parents[] = $sectorsParentId;
        }
    endwhile;
    $arrayAllSector = [];
    foreach($collect_parents as $parent): ?>
        <!-- Create format json sector and children -->
        <?php $currentPostId = $parent;
        $args = array(
            'post_type' => 'settore',
            'post_parent' => $currentPostId
        );
        $posts = new WP_Query($args);
        if( $posts->have_posts() ):
            while( $posts->have_posts() ) :
            $posts->the_post();
            $arrayAllSector[] = get_the_ID();
            endwhile;
        endif;
    endforeach;
    $args = array(
        'post_type' => 'test',
        'post_status' => 'publish',
    );
    $loop = new WP_Query( $args );
    $sectorUser= $userMeta['sector'][0];
    $sectorValueUser= json_decode($sectorUser);
    $sectorCurrentUser = array($sectorValueUser->idParent,$sectorValueUser->idChild);
    return array('loop'=>$loop,'arrayAllSector'=>$arrayAllSector,'sectorCurrentUser' =>$sectorCurrentUser);
}
